version: 2.1

workflows:
    version: 2
    build-and-publish:
        jobs:
            - build-and-publish-image:
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          ignore: /.*/

executors:
    docker-publisher:
        environment:
            IMAGE_NAME: erdkse/calculation-api
        docker:
            - image: erdkse/docker-with-buildx:v0.0.3

jobs:
    build-and-publish-image:
        executor: docker-publisher
        steps:
            - checkout
            - setup_remote_docker
            - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            - run:
                  name: Build and Publish Docker image
                  command: |
                      TAG=$(git describe $(git rev-list --tags --max-count=1))
                      docker buildx build --push \
                        --platform linux/amd64,linux/arm64 \
                        -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
